# python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/1.0.0.yaml

project_name: "personalvibe"
mode: milestone
execution_details: |
  specifically, please consider the following in your milestone generation:

  validate that my approach in vibe_utils and run_pipeline looks sufficient to build out milestone and sprint stages
  We do not want to provide this for non-Python users yet, we are still mid development of the core self-testing on the core personalvibe

  In my opinion, the most important thing to do next is to ensure that logs are being correctly saved to logs/{semver}_base.log
  we should test for this
  any testing directions created by 'validate' must be run using nox and have the ability to append results
  to logs/{semver}_base.log for any service called (pytest specifically but could later include flask, etc)

  The first sprint should also specify the creation and contents of a tests/personalvibe.sh
  We should be able to input a nox command to run validation of a sprint as per the sprint name (i.e. 1.1.0)

code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
milestone_file_name: ""
