# python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/1.2.0.yaml

project_name: "personalvibe"
mode: milestone
execution_details: |
  Demonstration of schema v2 (conversation_history enabled).

code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"

conversation_history:
  - role: user
    content: "Hi personalvibe — what’s next?"
  - role: assistant
    content: "We should upgrade the schema to v2!"
