# python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/2.0.0.yaml

project_name: "personalvibe"
mode: milestone
execution_details: |
  specifically, please consider the following in your milestone generation:

  We do not want to provide this for non-Python users yet, we are still mid development of the core self-testing on the core personalvibe

  The logs appear to be well setup.
  The next priority is to tighten the loop between sprint + error automation
  and auto-validation (up to 5 retries before rollback

  Also to directly parse the python markdown looking for ```python tagging

  All yaml config with 'sprint' should also kick off validation.

  We will add further parameterization to the process using yaml key: conversation_history
  A list of dict(role: user|assistant, content: value.read_text())

code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
milestone_file_name: ""
