# python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/2.0.0.yaml

project_name: "personalvibe"
mode: milestone
execution_details: |

  I want to start using my personalvibe project as a tool in other projects.

  Currently my personalvibe project sits in this directory:
  - `/Users/bytedance/Documents/personalvibe/`
  with subdirectories like
  - `/Users/bytedance/Documents/personalvibe/prompts/personalvibe/configs/2.0.0.yaml`
  - `/Users/bytedance/Documents/personalvibe/src/personalvibe/run_pipeline.py`

  I have another major project on my system like 
  - `/Users/bytedance/Documents/transparency_reporting/`

  I am able to generate a python wheel file such as `/Users/bytedance/Documents/personalvibe/dist/personalvibe-0.1.0-py3-none-any.whl`

  My plan is to perform a pip install in my other project,
  so it seems like I need a script interface instead of `python -m personalvibe.run_pipeline` i.e. `pv`

  I also need to rethink how pathing works - the idea being that the base directory in which it's called can generate the folders
  like data/ if needed

code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
milestone_file_name: ""
