# python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/2.3.1.yaml

# 1️⃣ Chunk A – CLI scaffolding
# 2️⃣ Chunk B – Path-resolution refactor
# 3️⃣ Chunk C – Data-directory bootstrap
# 4️⃣ Chunk D – Packaging & smoke-test
# 5️⃣ Chunk E – Documentation & examples

project_name: "personalvibe"
mode: sprint
execution_details: |

  Perform bugfix work for 3️⃣ Chunk C – Data-directory bootstrap based on the following

  (personalvibe-py3.9) bytedance@C02H86S6Q05N personalvibe % python -m personalvibe.run_pipeline --config prompts/personalvibe/configs/2.3.0.yaml
  2025-05-21 12:44:10 | INFO | __main__ | P  E  R  S  O  N  A  L  V  I  B  E  – run_id=2.3.0_base
  2025-05-21 12:44:10 | INFO | personalvibe.vibe_utils | Running config version: 2.3.0
  2025-05-21 12:44:10 | INFO | personalvibe.vibe_utils | Running mode = sprint
  2025-05-21 12:44:10 | INFO | personalvibe.vibe_utils | Prompt saved to: /Users/bytedance/Documents/personalvibe/data/personalvibe/prompt_inputs/2025-05-21_12-44-10_893ba89995.md
  2025-05-21 12:44:10 | INFO | personalvibe.vibe_utils | Prompt size – Tokens: 20934, Chars: 79417
  2025-05-21 12:44:45 | INFO | httpx | HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
  2025-05-21 12:44:45 | INFO | personalvibe.vibe_utils | Prompt saved to: /Users/bytedance/Documents/personalvibe/data/personalvibe/prompt_outputs/2025-05-21_12-44-45_893ba89995_08e008e3a5.md
  (personalvibe-py3.9) bytedance@C02H86S6Q05N personalvibe % python -m personalvibe.parse_stage --project_name personalvibe --run
  Saved extracted code to: /Users/bytedance/Documents/personalvibe/prompts/personalvibe/stages/2.3.0.py
  Running extracted code from: /Users/bytedance/Documents/personalvibe/prompts/personalvibe/stages/2.3.0.py
  Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Users/bytedance/Documents/personalvibe/src/personalvibe/parse_stage.py", line 98, in <module>
      runpy.run_path(saved_file, run_name="__main__")
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 268, in run_path
      return _run_module_code(code, init_globals, run_name,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 97, in _run_module_code
      _run_code(code, mod_globals, init_globals,
    File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/Users/bytedance/Documents/personalvibe/prompts/personalvibe/stages/2.3.0.py", line 132, in <module>
      _patch_file(VU_PATH, NEW_VU_CODE, ANCHOR_PATTERN, _PATCH_COMMENT)
    File "/Users/bytedance/Documents/personalvibe/prompts/personalvibe/stages/2.3.0.py", line 53, in _patch_file
      raise RuntimeError(f"Anchor pattern not found in {path}")
  RuntimeError: Anchor pattern not found in /Users/bytedance/Documents/personalvibe/src/personalvibe/vibe_utils.py
  (personalvibe-py3.9) bytedance@C02H86S6Q05N personalvibe %

code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
milestone_file_name: ""
