# pv run --config prompts/personalvibe/configs/7.2.0.yaml

# Chunk 1: Bug Fixes and Infrastructure Improvements
# Chunk 2: Bugfix Mode Implementation
# Chunk 3: Developer Experience Enhancements
# Chunk 4: Testing and Documentation

project_name: "personalvibe"
mode: sprint
model: anthropic/claude-opus-4-20250514
# model: openai/o3
# model: openai/o4-mini
# model: openai/gpt-4o
code_context_paths:
  - "prompts/personalvibe/context/documentation.txt"
  - "prompts/personalvibe/context/codefiles.txt"
execution_details: |
  Perform work for Chunk 2: Bugfix Mode Implementation
