# pv run --config prompts/personalvibe/configs/8.1.2.yaml

project_name: "personalvibe"
task: streamline
model: openai/o3-pro
project_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
user_instructions: |
  Perform streamlining analysis
