# pv run --config prompts/personalvibe/configs/8.1.0.yaml

# Chunk 1: Docker Environment Manager (Priority 1)
# Chunk 2: Sandboxed Execution Engine (Priority 2)
# Chunk 3: Test Suite Integration (Priority 3)
# Chunk 4: Enhanced Configuration and CLI Integration (Priority 4)
# Chunk 5: Retry Logic and Error Handling Enhancement (Priority 5)

project_name: "personalvibe"
task: sprint
# model: anthropic/claude-opus-4-20250514
# model: anthropic/claude-sonnet-4-20250514
# model: openai/o3
model: openai/o4-mini
# model: openai/gpt-4o
project_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
user_instructions: |
  Perform work for Chunk 1: Docker Environment Manager (Priority 1)
