# pv run --config prompts/personalvibe/configs/8.3.0.yaml

project_name: "personalvibe"
mode: sprint
# model: anthropic/claude-opus-4-20250514
model: anthropic/claude-sonnet-4-20250514
# model: openai/o3
# model: openai/o4-mini
# model: openai/gpt-4o
code_context_paths:
  - "prompts/personalvibe/context/codefiles.txt"
execution_details: |
  Perform work for
