/* Auto-generated by Chunk C (React fetch layer).  Edit manually if backend schemas evolve. */
// Generic “{ status, data, meta }” envelope returned by API
export interface ApiResponse<T> {
  status: 'ok';
  data: T;
  meta?: Pagination;
}

export interface Pagination {
  page: number;
  per_page: number;
  total: number;
  pages?: number;
}

// ────────────────────────────────────────────
// Domain models (Book, Character …)
// ────────────────────────────────────────────
export type CharacterType = 'adult' | 'child' | 'toy';

export interface Character {
  id: string;
  name: string;
  type: CharacterType;
  description: string;
  avatar_path?: string | null;
  created_at: string;           // ISO-8601
}

export interface Book {
  id: string;
  name: string;
  description: string;
  created_at: string;
  cover_image?: string | null;
  page_count: number;
}

// ────────────────────────────────────────────
// Auth DTOs
// ────────────────────────────────────────────
export interface LoginResponse {
  access_token: string;
  token_type: string;   // "bearer"
}

export interface MeResponse {
  id: string;
  email: string;
  display_name: string;
}
