/* Autogenerated by Chunk D – strongly-typed DTOs shared across UI  */

// ---------- Generic API envelope ----------
export interface ApiResponse<T = any> {
  status: 'ok' | 'error';
  data: T;
  meta?: any;
  error?: string;
}

// ---------- Domain models -----------------
export interface Character {
  id: string;
  name: string;
  type: 'adult' | 'child' | 'toy';
  description: string;
  avatar_path?: string | null;
  created_at?: string;
}

export interface Book {
  id: string;
  name: string;
  description: string;
  created_at: string;   // ISO
  cover_image?: string | null;
  page_count: number;
}

// ---------- Auth helpers ------------------
export interface LoginResponse {
  access_token: string;
  token_type: string;
}

export interface MeResponse {
  id: string;
  email: string;
  display_name: string;
}
