name: Pages

on:
  push:
    branches: [master]   # or main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - run: pip install nox==2025.2.9 poetry==2.1.1
      - run: poetry install
      - run: poetry run nox -s docs       # generates docs/_build/html

      # Explicit, fully-qualified artefact upload
      - uses: actions/upload-artifact@v4
        with:
          name: pages
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - id: deploy
        uses: actions/deploy-pages@v3
