name: "Sphinx docs to gh-pages"

on:
  push:
    branches:
      - main
      - master
      - staging/*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
        architecture: x64

    - name: Pip
      run: pip install nox==2025.2.9 poetry==2.1.1

    - name: Install
      run: poetry install

    - name: Build docs
      run: poetry run nox -s docs

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/_build
