name: Pages

on:
  push:
    branches: [master]       # or 'main'

permissions:
  contents: read
  pages: write        # lets the deploy action push
  id-token: write     # OIDC for the deploy action

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - run: pip install nox==2025.2.9 poetry==2.1.1
      - run: poetry install
      - run: poetry run nox -s docs   # builds to docs/_build/html

      # 1) upload the static site as an artifact
      - uses: actions/upload-pages-artifact@v2
        with:
          path: docs/_build/html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # 2) deploy the artifact to Pages
    steps:
      - id: deployment
        uses: actions/deploy-pages@v3
