name: Tests & Publish

on:
  # normal CI for every push *plus* publish when the push is a tag
  push:
    branches: [ "*" ]
    tags:     [ "v*" ]   # e.g. v2.1.0

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install nox==2025.2.9
      - run: pip install poetry==2.1.1
      - run: poetry install
      - run: poetry run nox -s release tests --force-python=${{ matrix.python-version }}
      # make the wheel + sdist available to the next job
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build-test
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      # 1️⃣  get the source tree (for pyproject.toml, poetry.lock, etc.)
      - uses: actions/checkout@v2

      # 2️⃣  set up Python exactly like in your other jobs
      - uses: actions/setup-python@v1
        with:
          python-version: '3.12'
          architecture: x64

      # 3️⃣  install Poetry (same pinned version)
      - run: pip install poetry==2.1.1

      # 4️⃣  pull in the wheel/sdist built by the previous job
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist

      # 5️⃣  upload to PyPI
      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          poetry publish \
            --username __token__ \
            --password "$POETRY_PYPI_TOKEN_PYPI" \
            --no-interaction
