name: Tests
on: push

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.12]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install nox==2025.2.9
    - run: pip install poetry==2.1.1
    - run: poetry install
    - run: poetry run nox --force-python=${{ matrix.python-version }}
